# CURSO DE NUMPY

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [1]:
import numpy as np

# gerando um array de tamanho 10;
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# Importando apenas um pacote do numpy
from numpy import arange
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# criando um array numpy
km = np.array([1000, 2300, 4987, 1500])
km
type(km)

numpy.ndarray

In [4]:
# chamando o tipo de array
km.dtype

dtype('int32')

In [5]:
# criando dados a partir de fontes externas;
km = np.loadtxt(fname = 'carros-km.txt', dtype = int)
km.dtype

dtype('int32')

In [6]:
# arrays com duas dimensões;
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático',
     'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
     'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
     'Painel digital', 'Piloto automático', 'Bancos de couro',
     'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular',
     'Freios ABS', 'Câmbio automático', 'Bancos de couro',
     'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [7]:
Acessorios = np.array(dados)

In [8]:
# verificando a dimensão do array
km.shape
Acessorios.shape

(3, 8)

In [9]:
# comparando desempenho de listas;
np_array = np.arange(1000000)
py_list = list(range(1000000))

In [11]:
# testando performace usando %time
%time for _ in range(100): np_array *= 2

Wall time: 260 ms


In [12]:
# testando performace usando %time
%time for _ in range(100): py_list = [x * 2 for x in py_list]

Wall time: 31.6 s


In [14]:
# Operações aritméticas com numpy;
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]
# não podemos fazer contas apenas com listas python, mas é possível com np;

In [15]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])
idade = 2021 - anos
idade

array([18, 30, 31,  2, 15])

In [16]:
# Operações entre arrays;
# forma1
km_media = km / idade
km_media.round(2)

array([2467.22,  190.4 , 1197.52,    0.  , 1717.13])

In [20]:
# Operações com array de duas dimensões;
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [21]:
# verificando a dimensão da matriz;
dados.shape

(2, 5)

In [22]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# chamando o elemento pela linha e coluna
dados[1, 2] # forma 1

1990.0

In [25]:
dados[1][2] # forma 2

1990.0

In [26]:
# realizando fatiamentos;
contador[1:4]

array([1, 2, 3])

In [27]:
# realizando fatiamento com passo de 2 em 2
contador[1:8:2]

array([1, 3, 5, 7])

In [28]:
# selecionando somente por colunas
dados[:, 1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [29]:
# realizando conta com elementos especificos do array;
dados[:, 1:3][0] / (2021 - dados[:, 1:3][1])

array([ 190.4       , 1197.51612903])

In [30]:
# Indexação com arrays booleanos;
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
contador > 5


array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [33]:
contador[[False, False, False, False, False, False,  True,  True,  True,
        True]]

array([6, 7, 8, 9])

In [34]:
# verificando apenas dados acima dos anos 2000;
dados[1] > 2000

array([ True, False, False,  True,  True])

# ATRIBUTOS E MÉTODOS COM ARRAYS NUMPY

In [35]:
# .shape -> retorna uma tupla  com as dimensões do array
dados.shape

(2, 5)

In [36]:
# .ndim -> reotorna o numero de dimensoes do array
dados.ndim

2

In [37]:
# .size -> retorna o nº de elementos no array
dados.size

10

In [38]:
# .dtype -> retorna o tipo de elemento dentro do array;
dados.dtype

dtype('float64')

In [39]:
# .T (transpose())-> retorna um array transposto, ou seja, converte linhas
# em colunas e vice versa;
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [40]:
# ltolist -> tranforma um array numpy em uma lista
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [41]:
# .reshape(shape[, order]) -> retorna um array que contem os mesmos 
# dados com uma nova formula;
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
contador.reshape((5, 2))
# acima modificamos para 5 linhas e duas colunas;

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
# usando indexação da liguagem C e FORTRAN
contador.reshape((5, 2), order='C')
contador.reshape((5, 2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [44]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [45]:
info_carros = km + anos
info_carros

[44410.0, 5712.0, 37123.0, 0.0, 25757.0, 2003, 1991, 1990, 2019, 2006]

In [46]:
np.array(info_carros).reshape((2, 5))
np.array(info_carros).reshape((5, 2), order='F')

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [47]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [48]:
dados_new.resize((3, 5), refcheck=False)
dados_new
# acima ele cria mais uma linha;

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [49]:
dados_new[2] = dados_new[0] / (2021 - dados_new[1])
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2467.22222222,   190.4       ,  1197.51612903,     0.        ,
         1717.13333333]])

In [50]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [51]:
# transformando um array unidimensional em colunas de uma array bidimensional;
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [52]:
dataset.shape

(258, 3)

In [53]:
# calculando a média
np.mean(dataset, axis = 0)
np.mean(dataset[:, 1])
np.mean(dataset[:, 2])

98960.51310077519

In [54]:
# calculando desvio padrao do valor;
np.std(dataset[:, 2])

29754.101150388564

In [55]:
# somatorios;
# forma 1
dataset.sum(axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [56]:
# forma 2
dataset[:, 1].sum()

11480849.0

In [57]:
# forma 3
np.sum(dataset, axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [58]:
# forma 4
np.sum(dataset[:, 2])

25531812.38