In [7]:
# aprendendo mais do numpy no https://www.w3schools.com/python/numpy_intro.asp
# usando um array
import numpy as np
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [3]:
# verificando o tipo
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
# dimensões de array;
# 1 dimensão
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [12]:
# dimensões de array;
# 2 dimensões
array2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
# dimensões de array;
# 3 dimensões
array2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

array([1, 2, 3, 4, 5])

In [19]:
# imprimindo elementos;
import numpy as np
array = np.array(range(1, 11))
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# imprimindo a 4ª posição, lembrando que sempre começa do 0, 1, 2 ...
print(array[4])

5


In [21]:
# operações com posições do array
import numpy as np
array = np.array(range(1, 11))
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# somando posições no exemplo 3 + 4 = 7
array[2] + array[3]

7

In [23]:
# multiplicando posições no exemplo 3 + 4 = 7
array[2] * array[3]

12

In [24]:
# subtraindo posições no exemplo 3 + 4 = 7
array[2] - array[3]

-1

In [25]:
# dividindo posições no exemplo 3 + 4 = 7
array[2] / array[3]

0.75

In [ ]:
# parei em NumPy Array Slicing